# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useSSL=false&serverTimezone=Asia/Shanghai
      username:  root
      password:  123456
      initialSize:  20
      maxActive:  50
      minIdle:  5
      maxWait:  5000

mybatis-plus:
  mapper-location:  classpath*:mapper/*.xml
  type-aliases-package:  com.qf.pojo
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl